<?php

use yii\helpers\Html;
$this->title= "Conclusion";
$this->params['breadcrumbs'][] = $this->title;
?>
<link href='http://fonts.googleapis.com/css?family=Open+Sans|Maven+Pro:500' rel='stylesheet' type='text/css'>

<header class="jumbotron" style="background-size: 100% auto; height: 600px;">
  <h1>In Conclusion</h1>
  <h3>We liked it.</h3>
</header>

<section>
  <a class="arrow-wrap" href="#content">
    <span class="arrow"></span>
    <!--<span class="hint">scroll</span>-->
  </a>
  <div class="content" id="content">
    <h1>Our Experience with Yii</h1>
    <p>
      Overall, our team enjoyed using Yii. We found it easy to install, easy to use, and forgiving of mistakes. Yii autogenerated a lot of the code that we needed to complete this project, including a great deal of the formating, the CRUD tool, and the model. We found the framework easy to learn, but hard to master. We felt that while we understood enough to create a functional and attractive website, some of the more powerful and complex features were beyond our grasp.
    </p>
    <p>
      We do not regret our choice. Yii is a competive framework that every developer should consider for their next project.
    </p>
</section>
